
@startuml

participant Client 
participant Empleat
participant Sistema

Client->Empleat: Truca a l'empresa
Empleat->Sistema: Genera fitxa Client
Empleat --> Client: Solicita Nom del Client
Client -> Empleat: Li dona el nom
Empleat -> Sistema: Retorna el Nom del Client
Empleat --> Client: Solicita Cognom del Client
Client -> Empleat: Li dona el Cognom
Empleat -> Sistema: Retorna el Cognom del Client
Empleat --> Client: Solicita DNI del Client
Client -> Empleat: Li dona el DNI
Empleat -> Sistema: Retorna el DNI del Client
Sistema->Sistema: Guarda el registre del nou client

@enduml