@startuml


:Empresa:
:Xofers:
:Gerent:

package Base_de_dades{
    (Donar alta clients) as Alta
    (Donar alta viatges) as Viatges
    (Client) as Client
    (Xofer) as Xofer
    (Adreça origen) as Origen
    (Adreça destí) as Desti
    (Data i hora de sortida) as Horari
    (Lliure) as Lliure
    (Cancelar)
    (Confirmar)
    (Donar alta Xofers) as Cotxe
    (Liquidacions) as diners
}   

Empresa-->Alta
Empresa-->Viatges
(Viatges)..>Client
(Viatges)..>Xofer
(Viatges)..>Origen
(Viatges)..>Desti
(Viatges)..>Horari
(Lliure)..>(Xofer):  Include
Empresa-->(Cancelar)
Empresa-->(Confirmar)
(Alta)..>(Client):  si el client no està donat d'alta
Xofers-->Horari: Select
Gerent--> Cotxe
Gerent-->diners
(Xofer)..>diners: Include



@enduml